services:
  app:
    build: .
    container_name: collection-tracker-app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    expose:
      - "5000"
    networks:
      - edge

networks:
  edge:
    name: edge
    external: true
